new end point for "/api/studies/by/{username}"
lichess-org/berserk pull request #41
Opened 2023-08-11 08:12 UTC by komalsai5135

2023-08-11 08:33 UTC, komalsai5135 commented
can anyone help me for that one failed test .

2023-08-11 09:08 UTC, kraktus commented
Hello, run `make format` and commit the changes

2023-08-11 14:32 UTC, icp1994 requested changes

2023-08-11 14:32 UTC, icp1994 commented on berserk/clients/studies.py
> +from typing import Any, Dict, Generator, Iterator
```suggestion
from typing import Any, Dict, Iterator
```

2023-08-11 14:32 UTC, icp1994 commented on berserk/clients/studies.py
> +from ..formats import PGN, JSON
```suggestion
from ..formats import PGN, NDJSON
```

2023-08-11 14:32 UTC, icp1994 commented on berserk/clients/studies.py
> +    def get_study_by_username(
`client.studies.get_study_by_username` is probably too verbose, I'd rather go with just `by_user`

2023-08-11 14:32 UTC, icp1994 commented on berserk/clients/studies.py
> +        # end point for api/study/by/{username}
This is not documenting what it does. See other endpoint definitions for example.

2023-08-11 14:32 UTC, icp1994 commented on berserk/clients/studies.py
> +        yield from self._r.get(path, fmt=JSON, stream=True)
```suggestion
        yield from self._r.get(path, fmt=NDJSON, stream=True)
```
streaming endpoints are always NDJSON or PGN

2023-08-11 14:32 UTC, icp1994 commented on README.rst
> +    client.studies.get_study_by_username
see name note below

2023-08-11 14:34 UTC, icp1994 commented on berserk/clients/studies.py
> +    ) -> Generator[Dict[str, Any], None, None]:
```suggestion
    ) -> Iterator[Dict[str, Any]]:
```

2023-08-13 19:49 UTC, merged

2023-08-13 19:57 UTC, kraktus commented
Thanks for the PR, I've made some changes (see commits above)