added /api/bot/online API
lichess-org/berserk pull request #8
Opened 2023-05-11 16:19 UTC by kalpgarg

Added REST endpoint for /api/bot/online.

This is to implement the first task in the issue https://github.com/lichess-org/berserk/issues/6. 

This is my first PR for this project. If this PR is ok, I plan to implement all the tasks under this issue.

All tests are getting passed when run locally.

2023-05-11 17:35 UTC, icp1994 requested changes

2023-05-11 17:35 UTC, icp1994 commented on README.rst
> +    client.bots.online
```suggestion
    client.bots.get_online_bots
```

2023-05-11 17:35 UTC, icp1994 commented on berserk/clients.py
> +        :param limit: Maximum number of bot users to fetch
```suggestion
        :param limit: Maximum number of bot users to fetch
        :type limit: int, optional
```

2023-05-11 17:35 UTC, icp1994 commented on berserk/clients.py
> +        :return: Iterator over the results
```suggestion
        :return: Iterator over the results
        :return: iterator over online bots
```

2023-05-11 17:35 UTC, icp1994 commented on berserk/clients.py
> +        path = f"api/bot/online"
```suggestion
        path = "api/bot/online"
```

2023-05-11 17:35 UTC, icp1994 commented on berserk/clients.py
> +        return self._r.get(path, params=params, stream=True)
```suggestion
        yield from self._r.get(
            path, params=params, stream=True, fmt=NDJSON, converter=models.User.convert
        )
```

2023-05-12 04:31 UTC, kalpgarg commented
Thanks, @icp1994, for your suggestions. I incorporated them all in the last commit.

2023-05-12 08:32 UTC, icp1994 reviewed
Thank you, looks good. There's just one line I forgot to remove in yesterday's review. After you are done, please squash/fixup your commits into one. The msg should be something like: "Add /api/bot/online endpoint"

2023-05-12 08:32 UTC, icp1994 commented on berserk/clients.py
> +        :return: Iterator over the results
```suggestion
```

2023-05-12 09:41 UTC, kalpgarg commented
Done @icp1994

2023-05-12 14:38 UTC, icp1994 approved these changes

2023-05-13 21:28 UTC, merged

2023-05-13 21:44 UTC, benediktwerner commented
Thanks! Release as v0.12.1